name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: index-html # replace with the name of your Docker image
  IMAGE_TAG: ${{ github.sha }} # tag the image with the current commit SHA
  KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG }} # the name of the secret containing your kubeconfig
  DEPLOYMENT_FILE: deployment.yaml # replace with the path to your Kubernetes deployment file

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # replace with the name of the secret containing your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # replace with the name of the secret containing your Docker Hub password

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} # replace DOCKER_USERNAME with your Docker Hub username

      - name: Set up kubeconfig
        run: |
          echo "${{ env.KUBECONFIG_CONTENT }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ${{ env.DEPLOYMENT_FILE }}
