name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t cloudnutzer/index-html:latest .

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: |
        docker push cloudnutzer/index-html:latest

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy Deployment to Kubernetes
      run: |
        kubectl apply -f deployment.yaml

    - name: Deploy Service to Kubernetes
      run: |
        kubectl apply -f service.yaml
